version: '3'
services:
  flask:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: flask
    ports: 
      - 5005:5000
    environment:
      MONGODB_DATABASE: action-tracking
      MONGODB_USERNAME: TFUDE
      MONGODB_PASSWORD: ibgUaUDs3Ftic4M47C8KdCje
      MONGODB_HOSTNAME: mongodb
      PGID: 100 # Change / comment for different machine
      PUID: 1008 # Change / comment for different machine
    networks:
      - proxy
      - backend

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: TFUDE
      MONGO_INITDB_ROOT_PASSWORD: ibgUaUDs3Ftic4M47C8KdCje
      MONGO_INITDB_DATABASE: action-tracking
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
      PGID: 100 # Change / comment for different machine
      PUID: 1008 # Change / comment for different machine
    volumes:
      - ./data/db:/data/db
    networks:
      - backend

networks:
  proxy:
    external:
      name: proxy
  backend:
    driver: bridge
